/* ================================================================
   TableTop (Smart Shelf) - Restaurant POS Database Schema (MSSQL)
   ================================================================
   Modules:
     CUSTOMER - digital menu, table-side ordering, call waiter, feedback
     WAITER   - table board, serve-ready alerts, call handling
     KITCHEN  - digital tickets (orders + per-item status)
     ADMIN    - inventory, recipes, discounts, payments, sales analytics

   Conventions (match src/repositories/genericRepository.js):
     - PKs are NVARCHAR(64) uuid strings generated by the app (uuid v4)
     - Soft delete via is_deleted BIT (0 = active)
     - created_at defaults to SYSDATETIME(); app sets updated_at on UPDATE

   !! WARNING !!
   This script DROPS and recreates every POS table in the target DB.
   Back up the `tabletop` database before running.

   Run (-I required for the filtered unique indexes):
     sqlcmd -S "(localdb)\MSSQLLocalDB" -d tabletop -b -I -i 01_schema.sql
   ================================================================ */

USE tabletop;
GO

/* Required for the filtered unique indexes below (sqlcmd defaults this OFF;
   run with -I or rely on these SETs). */
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

/* ---------------- drop views ---------------- */
IF OBJECT_ID('dbo.vw_kitchen_queue',    'V') IS NOT NULL DROP VIEW dbo.vw_kitchen_queue;
IF OBJECT_ID('dbo.vw_waiter_board',     'V') IS NOT NULL DROP VIEW dbo.vw_waiter_board;
IF OBJECT_ID('dbo.vw_low_stock',        'V') IS NOT NULL DROP VIEW dbo.vw_low_stock;
IF OBJECT_ID('dbo.vw_daily_sales',      'V') IS NOT NULL DROP VIEW dbo.vw_daily_sales;
IF OBJECT_ID('dbo.vw_item_sales',       'V') IS NOT NULL DROP VIEW dbo.vw_item_sales;
GO

/* ---------------- drop tables (reverse dependency order) ---------------- */
IF OBJECT_ID('dbo.inventory_logs',       'U') IS NOT NULL DROP TABLE dbo.inventory_logs;
IF OBJECT_ID('dbo.feedback',             'U') IS NOT NULL DROP TABLE dbo.feedback;
IF OBJECT_ID('dbo.waiter_calls',         'U') IS NOT NULL DROP TABLE dbo.waiter_calls;
IF OBJECT_ID('dbo.payments',             'U') IS NOT NULL DROP TABLE dbo.payments;
IF OBJECT_ID('dbo.order_process',        'U') IS NOT NULL DROP TABLE dbo.order_process;
IF OBJECT_ID('dbo.orders_and_discounts', 'U') IS NOT NULL DROP TABLE dbo.orders_and_discounts;
IF OBJECT_ID('dbo.order_details',        'U') IS NOT NULL DROP TABLE dbo.order_details;
IF OBJECT_ID('dbo.orders',               'U') IS NOT NULL DROP TABLE dbo.orders;
IF OBJECT_ID('dbo.discounts',            'U') IS NOT NULL DROP TABLE dbo.discounts;
IF OBJECT_ID('dbo.recipes_inventory',    'U') IS NOT NULL DROP TABLE dbo.recipes_inventory;
IF OBJECT_ID('dbo.inventory',            'U') IS NOT NULL DROP TABLE dbo.inventory;
IF OBJECT_ID('dbo.menu_item',            'U') IS NOT NULL DROP TABLE dbo.menu_item;
IF OBJECT_ID('dbo.categories',           'U') IS NOT NULL DROP TABLE dbo.categories;
IF OBJECT_ID('dbo.tables',               'U') IS NOT NULL DROP TABLE dbo.tables;
IF OBJECT_ID('dbo.user_logs',            'U') IS NOT NULL DROP TABLE dbo.user_logs;
IF OBJECT_ID('dbo.staff',                'U') IS NOT NULL DROP TABLE dbo.staff;
IF OBJECT_ID('dbo.roles_and_users',      'U') IS NOT NULL DROP TABLE dbo.roles_and_users;
IF OBJECT_ID('dbo.roles',                'U') IS NOT NULL DROP TABLE dbo.roles;
IF OBJECT_ID('dbo.users',                'U') IS NOT NULL DROP TABLE dbo.users;
GO

/* ================================================================
   SHARED / AUTH
   ================================================================ */

CREATE TABLE dbo.users (
  user_id     NVARCHAR(64)  NOT NULL CONSTRAINT PK_users PRIMARY KEY,
  first_name  NVARCHAR(255) NOT NULL,
  last_name   NVARCHAR(255) NOT NULL,
  email       NVARCHAR(255) NOT NULL,
  password    NVARCHAR(255) NOT NULL,              -- bcrypt hash
  is_active   BIT           NOT NULL CONSTRAINT DF_users_active  DEFAULT 1,
  created_at  DATETIME2     NOT NULL CONSTRAINT DF_users_created DEFAULT SYSDATETIME(),
  updated_at  DATETIME2     NULL,
  is_deleted  BIT           NOT NULL CONSTRAINT DF_users_deleted DEFAULT 0
);
GO
CREATE UNIQUE NONCLUSTERED INDEX UQ_users_email
  ON dbo.users (email) WHERE is_deleted = 0;
GO

CREATE TABLE dbo.roles (
  role_id     NVARCHAR(64)  NOT NULL CONSTRAINT PK_roles PRIMARY KEY,
  role_name   NVARCHAR(100) NOT NULL,              -- 'admin' | 'waiter' | 'kitchen'
  created_at  DATETIME2     NOT NULL CONSTRAINT DF_roles_created DEFAULT SYSDATETIME(),
  updated_at  DATETIME2     NULL,
  is_deleted  BIT           NOT NULL CONSTRAINT DF_roles_deleted DEFAULT 0
);
GO

/* NOTE: PK column is roles_and_users_id (plural "roles") to match
   src/repositories/roleandstaffRepository.js — POS.sql had a typo. */
CREATE TABLE dbo.roles_and_users (
  roles_and_users_id NVARCHAR(64) NOT NULL CONSTRAINT PK_roles_and_users PRIMARY KEY,
  user_id            NVARCHAR(64) NOT NULL CONSTRAINT FK_ru_user REFERENCES dbo.users (user_id),
  role_id            NVARCHAR(64) NOT NULL CONSTRAINT FK_ru_role REFERENCES dbo.roles (role_id),
  created_at         DATETIME2    NOT NULL CONSTRAINT DF_ru_created DEFAULT SYSDATETIME(),
  updated_at         DATETIME2    NULL,
  is_deleted         BIT          NOT NULL CONSTRAINT DF_ru_deleted DEFAULT 0
);
GO

CREATE TABLE dbo.staff (
  staff_id    NVARCHAR(64)  NOT NULL CONSTRAINT PK_staff PRIMARY KEY,
  first_name  NVARCHAR(255) NOT NULL,
  last_name   NVARCHAR(255) NOT NULL,
  role_id     NVARCHAR(64)  NULL CONSTRAINT FK_staff_role REFERENCES dbo.roles (role_id),
  user_id     NVARCHAR(64)  NULL CONSTRAINT FK_staff_user REFERENCES dbo.users (user_id), -- login account, if any
  staff_code  NVARCHAR(20)  NULL,                 -- PIN typed on a customer tablet (ID verify, cash confirm)
  created_at  DATETIME2     NOT NULL CONSTRAINT DF_staff_created DEFAULT SYSDATETIME(),
  updated_at  DATETIME2     NULL,
  is_deleted  BIT           NOT NULL CONSTRAINT DF_staff_deleted DEFAULT 0
);
GO

CREATE TABLE dbo.user_logs (
  logs_id     NVARCHAR(64)  NOT NULL CONSTRAINT PK_user_logs PRIMARY KEY,
  users_id    NVARCHAR(64)  NOT NULL CONSTRAINT FK_ulogs_user REFERENCES dbo.users (user_id),
  logs_type   NVARCHAR(50)  NOT NULL,              -- 'login' | 'logout' | 'crud' | ...
  logs        NVARCHAR(500) NULL,
  created_at  DATETIME2     NOT NULL CONSTRAINT DF_ulogs_created DEFAULT SYSDATETIME(),
  updated_at  DATETIME2     NULL,
  is_deleted  BIT           NOT NULL CONSTRAINT DF_ulogs_deleted DEFAULT 0
);
GO

/* ================================================================
   CUSTOMER MODULE - tables, digital menu, orders, calls, feedback
   ================================================================ */

CREATE TABLE dbo.tables (
  table_id     NVARCHAR(64)  NOT NULL CONSTRAINT PK_tables PRIMARY KEY,
  table_name   NVARCHAR(100) NOT NULL,
  password     NVARCHAR(255) NOT NULL,             -- tablet login credential
  table_type   SMALLINT      NULL,
  is_available BIT           NOT NULL CONSTRAINT DF_tables_avail   DEFAULT 1,
  capacity     SMALLINT      NULL,
  created_at   DATETIME2     NOT NULL CONSTRAINT DF_tables_created DEFAULT SYSDATETIME(),
  updated_at   DATETIME2     NULL,
  is_deleted   BIT           NOT NULL CONSTRAINT DF_tables_deleted DEFAULT 0
);
GO
CREATE UNIQUE NONCLUSTERED INDEX UQ_tables_name
  ON dbo.tables (table_name) WHERE is_deleted = 0;
GO

CREATE TABLE dbo.categories (
  category_id   NVARCHAR(64)  NOT NULL CONSTRAINT PK_categories PRIMARY KEY,
  category_name NVARCHAR(100) NOT NULL,
  created_at    DATETIME2     NOT NULL CONSTRAINT DF_cat_created DEFAULT SYSDATETIME(),
  updated_at    DATETIME2     NULL,
  is_deleted    BIT           NOT NULL CONSTRAINT DF_cat_deleted DEFAULT 0
);
GO

CREATE TABLE dbo.menu_item (
  menu_item_id NVARCHAR(64)  NOT NULL CONSTRAINT PK_menu_item PRIMARY KEY,
  category_id  NVARCHAR(64)  NOT NULL CONSTRAINT FK_menu_category REFERENCES dbo.categories (category_id),
  menu_title   NVARCHAR(255) NOT NULL,
  food_item    NVARCHAR(500) NULL,                 -- description shown on the tablet menu
  food_pic     NVARCHAR(500) NULL,                 -- image URL / path
  unit_price   DECIMAL(10,2) NOT NULL,
  status       NVARCHAR(20)  NOT NULL CONSTRAINT DF_menu_status DEFAULT 'available'
               CONSTRAINT CK_menu_status CHECK (status IN ('available','unavailable')),
  created_at   DATETIME2     NOT NULL CONSTRAINT DF_menu_created DEFAULT SYSDATETIME(),
  updated_at   DATETIME2     NULL,
  is_deleted   BIT           NOT NULL CONSTRAINT DF_menu_deleted DEFAULT 0
);
GO
CREATE NONCLUSTERED INDEX IX_menu_item_category ON dbo.menu_item (category_id);
GO

CREATE TABLE dbo.orders (
  orders_id  NVARCHAR(64) NOT NULL CONSTRAINT PK_orders PRIMARY KEY,
  table_id   NVARCHAR(64) NOT NULL CONSTRAINT FK_orders_table REFERENCES dbo.tables (table_id),
  staff_id   NVARCHAR(64) NULL     CONSTRAINT FK_orders_staff REFERENCES dbo.staff (staff_id), -- waiter who served
  status     NVARCHAR(20) NOT NULL CONSTRAINT DF_orders_status DEFAULT 'placed'
             CONSTRAINT CK_orders_status
             CHECK (status IN ('pending_payment','placed','in_progress','ready','served','paid','cancelled')),
             -- 'pending_payment': checked out but unpaid; invisible to kitchen/waiter boards
  order_date DATETIME2    NOT NULL CONSTRAINT DF_orders_date    DEFAULT SYSDATETIME(),
  created_at DATETIME2    NOT NULL CONSTRAINT DF_orders_created DEFAULT SYSDATETIME(),
  updated_at DATETIME2    NULL,
  is_deleted BIT          NOT NULL CONSTRAINT DF_orders_deleted DEFAULT 0
);
GO
CREATE NONCLUSTERED INDEX IX_orders_table  ON dbo.orders (table_id);
CREATE NONCLUSTERED INDEX IX_orders_status ON dbo.orders (status) INCLUDE (table_id, order_date);
GO

/* One row per line item = one kitchen "ticket line".
   status here is what the KITCHEN updates and the WAITER/CUSTOMER track. */
CREATE TABLE dbo.order_details (
  order_details_id NVARCHAR(64)  NOT NULL CONSTRAINT PK_order_details PRIMARY KEY,
  orders_id        NVARCHAR(64)  NOT NULL CONSTRAINT FK_od_order REFERENCES dbo.orders (orders_id),
  menu_item_id     NVARCHAR(64)  NOT NULL CONSTRAINT FK_od_menu  REFERENCES dbo.menu_item (menu_item_id),
  price            DECIMAL(10,2) NOT NULL,          -- unit price at time of order
  quantity         INT           NOT NULL CONSTRAINT CK_od_qty CHECK (quantity > 0),
  total            DECIMAL(10,2) NOT NULL,          -- app computes price * quantity
  notes            NVARCHAR(255) NULL,              -- customer special requests
  discount_id      NVARCHAR(64)  NULL,              -- discount holder's items (Senior/PWD);
                                                    -- FK added after dbo.discounts is created below
  status           NVARCHAR(20)  NOT NULL CONSTRAINT DF_od_status DEFAULT 'queued'
                   CONSTRAINT CK_od_status
                   CHECK (status IN ('queued','in_progress','ready_to_serve','served','cancelled')),
  created_at       DATETIME2     NOT NULL CONSTRAINT DF_od_created DEFAULT SYSDATETIME(),
  updated_at       DATETIME2     NULL,
  is_deleted       BIT           NOT NULL CONSTRAINT DF_od_deleted DEFAULT 0
);
GO
CREATE NONCLUSTERED INDEX IX_od_order  ON dbo.order_details (orders_id);
CREATE NONCLUSTERED INDEX IX_od_status ON dbo.order_details (status) INCLUDE (orders_id, menu_item_id);
GO

/* Customer taps "Call Waiter" on the tablet -> row lands here.
   Waiter dashboard polls / subscribes to status = 'pending'. */
CREATE TABLE dbo.waiter_calls (
  waiter_call_id  NVARCHAR(64)  NOT NULL CONSTRAINT PK_waiter_calls PRIMARY KEY,
  table_id        NVARCHAR(64)  NOT NULL CONSTRAINT FK_wc_table REFERENCES dbo.tables (table_id),
  request_type    NVARCHAR(30)  NOT NULL CONSTRAINT DF_wc_type DEFAULT 'call_waiter'
                  CONSTRAINT CK_wc_type
                  CHECK (request_type IN ('call_waiter','request_bill','assistance','other')),
  message         NVARCHAR(255) NULL,
  status          NVARCHAR(20)  NOT NULL CONSTRAINT DF_wc_status DEFAULT 'pending'
                  CONSTRAINT CK_wc_status CHECK (status IN ('pending','acknowledged','resolved')),
  acknowledged_by NVARCHAR(64)  NULL CONSTRAINT FK_wc_staff REFERENCES dbo.staff (staff_id),
  resolved_at     DATETIME2     NULL,
  created_at      DATETIME2     NOT NULL CONSTRAINT DF_wc_created DEFAULT SYSDATETIME(),
  updated_at      DATETIME2     NULL,
  is_deleted      BIT           NOT NULL CONSTRAINT DF_wc_deleted DEFAULT 0
);
GO
CREATE NONCLUSTERED INDEX IX_wc_status ON dbo.waiter_calls (status) INCLUDE (table_id, request_type);
GO

CREATE TABLE dbo.feedback (
  feedback_id NVARCHAR(64)  NOT NULL CONSTRAINT PK_feedback PRIMARY KEY,
  table_id    NVARCHAR(64)  NOT NULL CONSTRAINT FK_fb_table REFERENCES dbo.tables (table_id),
  orders_id   NVARCHAR(64)  NULL     CONSTRAINT FK_fb_order REFERENCES dbo.orders (orders_id),
  rating      TINYINT       NULL     CONSTRAINT CK_fb_rating CHECK (rating BETWEEN 1 AND 5),
  feedback    NVARCHAR(500) NULL,
  created_at  DATETIME2     NOT NULL CONSTRAINT DF_fb_created DEFAULT SYSDATETIME(),
  updated_at  DATETIME2     NULL,
  is_deleted  BIT           NOT NULL CONSTRAINT DF_fb_deleted DEFAULT 0
);
GO

/* ================================================================
   KITCHEN MODULE - order stage history (for prep-time analytics)
   ================================================================ */

CREATE TABLE dbo.order_process (
  order_process_id NVARCHAR(64) NOT NULL CONSTRAINT PK_order_process PRIMARY KEY,
  orders_id        NVARCHAR(64) NOT NULL CONSTRAINT FK_op_order REFERENCES dbo.orders (orders_id),
  stage            NVARCHAR(30) NOT NULL
                   CONSTRAINT CK_op_stage
                   CHECK (stage IN ('placed','in_progress','ready','served','paid','cancelled')),
  changed_by       NVARCHAR(64) NULL CONSTRAINT FK_op_staff REFERENCES dbo.staff (staff_id),
  started_at       DATETIME2    NOT NULL CONSTRAINT DF_op_started DEFAULT SYSDATETIME(),
  completed_at     DATETIME2    NULL,
  created_at       DATETIME2    NOT NULL CONSTRAINT DF_op_created DEFAULT SYSDATETIME(),
  updated_at       DATETIME2    NULL,
  is_deleted       BIT          NOT NULL CONSTRAINT DF_op_deleted DEFAULT 0
);
GO
CREATE NONCLUSTERED INDEX IX_op_order ON dbo.order_process (orders_id);
GO

/* ================================================================
   ADMIN MODULE - inventory, recipes, discounts, payments
   ================================================================ */

CREATE TABLE dbo.inventory (
  inventory_id      NVARCHAR(64)  NOT NULL CONSTRAINT PK_inventory PRIMARY KEY,
  item_name         NVARCHAR(255) NOT NULL,
  unit_of_measure   NVARCHAR(50)  NOT NULL,         -- 'kg' | 'g' | 'L' | 'pc' | ...
  quantity_in_stock DECIMAL(12,2) NOT NULL CONSTRAINT DF_inv_qty     DEFAULT 0,
  reorder_level     DECIMAL(12,2) NOT NULL CONSTRAINT DF_inv_reorder DEFAULT 0, -- low-stock alert threshold
  unit_cost         DECIMAL(10,2) NULL,
  available         BIT           NOT NULL CONSTRAINT DF_inv_avail   DEFAULT 1,
  created_at        DATETIME2     NOT NULL CONSTRAINT DF_inv_created DEFAULT SYSDATETIME(),
  updated_at        DATETIME2     NULL,
  is_deleted        BIT           NOT NULL CONSTRAINT DF_inv_deleted DEFAULT 0
);
GO

/* Recipe map: how much of each inventory item one menu item consumes. */
CREATE TABLE dbo.recipes_inventory (
  recipes_inventory_id NVARCHAR(64)  NOT NULL CONSTRAINT PK_recipes_inventory PRIMARY KEY,
  menu_item_id         NVARCHAR(64)  NOT NULL CONSTRAINT FK_ri_menu REFERENCES dbo.menu_item (menu_item_id),
  inventory_id         NVARCHAR(64)  NOT NULL CONSTRAINT FK_ri_inv  REFERENCES dbo.inventory (inventory_id),
  amount_needed        DECIMAL(12,2) NOT NULL CONSTRAINT CK_ri_amount CHECK (amount_needed > 0),
  created_at           DATETIME2     NOT NULL CONSTRAINT DF_ri_created DEFAULT SYSDATETIME(),
  updated_at           DATETIME2     NULL,
  is_deleted           BIT           NOT NULL CONSTRAINT DF_ri_deleted DEFAULT 0
);
GO
CREATE UNIQUE NONCLUSTERED INDEX UQ_ri_menu_inv
  ON dbo.recipes_inventory (menu_item_id, inventory_id) WHERE is_deleted = 0;
GO

/* Every stock movement, up or down. quantity_change is signed:
   negative = deduction (order fired), positive = restock/adjustment. */
CREATE TABLE dbo.inventory_logs (
  inventory_logs_id NVARCHAR(64)  NOT NULL CONSTRAINT PK_inventory_logs PRIMARY KEY,
  inventory_id      NVARCHAR(64)  NOT NULL CONSTRAINT FK_il_inv REFERENCES dbo.inventory (inventory_id),
  order_details_id  NVARCHAR(64)  NULL     CONSTRAINT FK_il_od  REFERENCES dbo.order_details (order_details_id),
  change_type       NVARCHAR(30)  NOT NULL
                    CONSTRAINT CK_il_type
                    CHECK (change_type IN ('order_deduction','restock','adjustment','spoilage')),
  quantity_change   DECIMAL(12,2) NOT NULL,
  created_at        DATETIME2     NOT NULL CONSTRAINT DF_il_created DEFAULT SYSDATETIME(),
  updated_at        DATETIME2     NULL,
  is_deleted        BIT           NOT NULL CONSTRAINT DF_il_deleted DEFAULT 0
);
GO
CREATE NONCLUSTERED INDEX IX_il_inventory ON dbo.inventory_logs (inventory_id);
GO

CREATE TABLE dbo.discounts (
  discount_id   NVARCHAR(64)  NOT NULL CONSTRAINT PK_discounts PRIMARY KEY,
  discount_type NVARCHAR(100) NOT NULL,             -- 'Senior Citizen', 'PWD', 'Promo', ...
  rate          DECIMAL(5,4)  NOT NULL CONSTRAINT CK_disc_rate CHECK (rate > 0 AND rate <= 1), -- 0.2000 = 20%
  created_at    DATETIME2     NOT NULL CONSTRAINT DF_disc_created DEFAULT SYSDATETIME(),
  updated_at    DATETIME2     NULL,
  is_deleted    BIT           NOT NULL CONSTRAINT DF_disc_deleted DEFAULT 0
);
GO

/* order_details.discount_id FK lives here because discounts is created later
   than order_details */
ALTER TABLE dbo.order_details ADD CONSTRAINT FK_od_discount
  FOREIGN KEY (discount_id) REFERENCES dbo.discounts (discount_id);
GO

/* One row per discount request on an order. status tracks the waiter's
   on-site ID verification (staff_code entered on the customer tablet). */
CREATE TABLE dbo.orders_and_discounts (
  orders_and_discounts_id NVARCHAR(64) NOT NULL CONSTRAINT PK_orders_and_discounts PRIMARY KEY,
  orders_id               NVARCHAR(64) NOT NULL CONSTRAINT FK_oad_order    REFERENCES dbo.orders (orders_id),
  discount_id             NVARCHAR(64) NOT NULL CONSTRAINT FK_oad_discount REFERENCES dbo.discounts (discount_id),
  status                  NVARCHAR(20) NOT NULL CONSTRAINT DF_oad_status DEFAULT 'pending'
                          CONSTRAINT CK_oad_status CHECK (status IN ('pending','approved','denied')),
  verified_by             NVARCHAR(64) NULL CONSTRAINT FK_oad_staff REFERENCES dbo.staff (staff_id),
  created_at              DATETIME2    NOT NULL CONSTRAINT DF_oad_created DEFAULT SYSDATETIME(),
  updated_at              DATETIME2    NULL,
  is_deleted              BIT          NOT NULL CONSTRAINT DF_oad_deleted DEFAULT 0
);
GO

/* Order-level payment record (replaces POS.sql orders.payment_method smallint).
   This is what sales analytics aggregates over. */
CREATE TABLE dbo.payments (
  payment_id     NVARCHAR(64)  NOT NULL CONSTRAINT PK_payments PRIMARY KEY,
  orders_id      NVARCHAR(64)  NOT NULL CONSTRAINT FK_pay_order REFERENCES dbo.orders (orders_id),
  payment_method NVARCHAR(20)  NOT NULL
                 CONSTRAINT CK_pay_method
                 CHECK (payment_method IN ('cash','card','gcash','maya','qrph','other')),
  amount         DECIMAL(10,2) NOT NULL CONSTRAINT CK_pay_amount CHECK (amount >= 0),
  status         NVARCHAR(20)  NOT NULL CONSTRAINT DF_pay_status DEFAULT 'pending'
                 CONSTRAINT CK_pay_status CHECK (status IN ('pending','paid','refunded','voided')),
  paid_at        DATETIME2     NULL,
  created_at     DATETIME2     NOT NULL CONSTRAINT DF_pay_created DEFAULT SYSDATETIME(),
  updated_at     DATETIME2     NULL,
  is_deleted     BIT           NOT NULL CONSTRAINT DF_pay_deleted DEFAULT 0
);
GO
CREATE NONCLUSTERED INDEX IX_pay_order ON dbo.payments (orders_id);
CREATE NONCLUSTERED INDEX IX_pay_paid  ON dbo.payments (status, paid_at) INCLUDE (amount);
GO

/* ================================================================
   MODULE VIEWS - ready-made queries for each dashboard
   ================================================================ */

/* KITCHEN: live ticket lines still to cook, oldest first.
   Orders in 'pending_payment' are invisible - payment fires them here. */
CREATE VIEW dbo.vw_kitchen_queue AS
SELECT
  od.order_details_id,
  o.orders_id,
  t.table_name,
  mi.menu_title,
  od.quantity,
  od.notes,
  od.status,
  od.created_at AS ordered_at
FROM dbo.order_details od
JOIN dbo.orders    o  ON o.orders_id     = od.orders_id     AND o.is_deleted  = 0
                     AND o.status IN ('placed','in_progress','ready')
JOIN dbo.tables    t  ON t.table_id      = o.table_id
JOIN dbo.menu_item mi ON mi.menu_item_id = od.menu_item_id
WHERE od.is_deleted = 0
  AND od.status IN ('queued','in_progress');
GO

/* WAITER: one row per table - what needs attention right now */
CREATE VIEW dbo.vw_waiter_board AS
SELECT
  t.table_id,
  t.table_name,
  t.is_available,
  (SELECT COUNT(*) FROM dbo.orders o
    WHERE o.table_id = t.table_id AND o.is_deleted = 0
      AND o.status IN ('placed','in_progress','ready'))                    AS open_orders,
  (SELECT COUNT(*) FROM dbo.orders o
    JOIN dbo.order_details od ON od.orders_id = o.orders_id AND od.is_deleted = 0
    WHERE o.table_id = t.table_id AND o.is_deleted = 0
      AND od.status = 'ready_to_serve')                                    AS items_ready_to_serve,
  (SELECT COUNT(*) FROM dbo.waiter_calls wc
    WHERE wc.table_id = t.table_id AND wc.is_deleted = 0
      AND wc.status = 'pending')                                           AS pending_calls
FROM dbo.tables t
WHERE t.is_deleted = 0;
GO

/* ADMIN: items at or below their reorder threshold */
CREATE VIEW dbo.vw_low_stock AS
SELECT inventory_id, item_name, unit_of_measure, quantity_in_stock, reorder_level
FROM dbo.inventory
WHERE is_deleted = 0
  AND quantity_in_stock <= reorder_level;
GO

/* ADMIN: gross sales per day (paid payments only) */
CREATE VIEW dbo.vw_daily_sales AS
SELECT
  CAST(p.paid_at AS DATE)       AS sales_date,
  COUNT(DISTINCT p.orders_id)   AS orders_count,
  SUM(p.amount)                 AS gross_sales
FROM dbo.payments p
WHERE p.is_deleted = 0 AND p.status = 'paid'
GROUP BY CAST(p.paid_at AS DATE);
GO

/* ADMIN: best sellers - quantity and revenue per menu item.
   An item counts as sold once its order has a paid payments row (the
   pay-before-kitchen flow pays up front, so orders end at 'served'). */
CREATE VIEW dbo.vw_item_sales AS
SELECT
  mi.menu_item_id,
  mi.menu_title,
  c.category_name,
  SUM(od.quantity) AS total_qty_sold,
  SUM(od.total)    AS total_revenue
FROM dbo.order_details od
JOIN dbo.orders     o  ON o.orders_id     = od.orders_id AND o.is_deleted = 0
JOIN dbo.menu_item  mi ON mi.menu_item_id = od.menu_item_id
JOIN dbo.categories c  ON c.category_id   = mi.category_id
WHERE od.is_deleted = 0 AND od.status <> 'cancelled'
  AND EXISTS (SELECT 1 FROM dbo.payments p
              WHERE p.orders_id = o.orders_id
                AND p.status = 'paid' AND p.is_deleted = 0)
GROUP BY mi.menu_item_id, mi.menu_title, c.category_name;
GO
